name: Template Java Weblogic

on:
  workflow_call:
    inputs:
      deploy_platform:
        description: "Plataforma de despliegue"
        required: true
        default: "linux"
        type: string
      artifacts_pattern:
        description: "Directorio o expresion regular que describe que se desea almacenar como artefacto"
        default: "build/ear/*ear"
        required: true
        type: string
      artifacts_name:
        description: "Nombre del Ear"
        default: "HelloWorld"
        required: true
        type: string
      java_version:
        description: "Version de Java del proyecto"
        required: true
        default: "11"
        type: string
      #Inputs para despliegue en consola Weblogic
      server_host:
        description: "Host del servidor WebLogic"
        required: true
        type: string
      server_port:
        description: "Puerto del servidor WebLogic"
        required: true
        type: string
      weblogic_user:
        description: "Usuario WebLogic"
        required: true
        type: string
      target_name:
        description: "Nombre del target WebLogic"
        required: true
        type: string
      app_name:
        description: "Nombre lógico de la app WebLogic"
        required: true
        type: string
      sonar_enabled:
        description: "Habilitar análisis SonarQube"
        required: false
        default: true  # <-- Sin comillas, valor booleano directo
        type: boolean  # <-- Tipo definido como boolean


jobs:
  BUILD:
    # Compila el proyecto con Ant y guarda artefactos
    uses: asantander90/chi-GitHub-Functions-main/.github/workflows/buildAnt.yml@main
    with:
      java_version: ${{ inputs.java_version }}
      artifacts_pattern: ${{ inputs.artifacts_pattern }}
    secrets: inherit
  
  SONAR:
    needs: BUILD
    if: ${{ inputs.sonar_enabled }}  # <-- se evalúa directo como booleano
    uses: asantander90/chi-GitHub-Functions-main/.github/workflows/sonarScan.yml@main
    secrets: inherit
    
  DEPLOY:
    needs: [BUILD, SONAR]
    if: ${{ !inputs.sonar_enabled || needs.SONAR.result == 'success' }}  # <-- Lógica booleana
    uses: asantander90/chi-GitHub-Functions-main/.github/workflows/deployWeblogic.yml@main
    with:
      artifacts_pattern: ${{ inputs.artifacts_pattern }}
      artifacts_name: ${{ inputs.artifacts_name }}
      server_host: ${{ inputs.server_host }}
      server_port: ${{ inputs.server_port }}
      weblogic_user: ${{ inputs.weblogic_user }}
      target_name: ${{ inputs.target_name }}
      app_name: ${{ inputs.app_name }}
    secrets: inherit


